import type { Metadata } from 'next';
import { Montserrat_Alternates } from 'next/font/google';

import '@/app/global-style/globals.css';
import '@/app/global-style/header.css';

import { ReactQueryProvider } from '@/components/ReactQueryProvider';

const montserratAlternates = Montserrat_Alternates({
  subsets: ['cyrillic'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-montserrat-alternates',
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    template: '%s | Online Shop',
    default: 'Online Shop',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      <html lang="ru">
        <body className={montserratAlternates.variable}>{children}</body>
      </html>
    </ReactQueryProvider>
  );
}
